In [2]:
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
c=a+b
print (c)
d=np.array([7,8,9])
e=np.array([[10,11,12],[13,14,15]])
f=d+e
print (f)

[5 7 9]
[[17 19 21]
 [20 22 24]]


Here if we observe a and b are of same dimensions so there the element wise operation has been done. But if we see in the second case there the dimensions of both d and e are not same but by using broadcasting numpy has expanded the d array to amtch with e and did the element wise operation. Numpy broadcasts when their dimensions are compatible.